version : '3.9'
services:
  # 关系型数据库
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    volumes:
      - /home/docker/mysql/conf:/etc/mysql/conf.d
      - /home/docker/mysql/logs:/var/log
      - /home/docker/mysql/data:/var/lib/mysql
      - /home/docker/mysql/mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: kun_mysql
    privileged: true
    restart: always
  # 缓存
  redis:
    container_name: redis
    image: redis:7.0.10
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/redis/redis.conf:/etc/redis/redis.conf
      - /home/docker/redis/data:/data
    privileged: true
    restart: always
    command: redis-server /etc/redis/redis.conf
  # 非结构化数据存储
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - /home/docker/minio/data:/data
      - /home/docker/minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=kun_minio
    privileged: true
    restart: always
    command: server /data --console-address ":9090" -address ":9000"
  # 消息队列
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=kun_rabbitmq
    privileged: true
    restart: always
  # 定时任务
  xxl-job-admin:
    container_name: xxl-job-admin
    image: xuxueli/xxl-job-admin:2.4.0
    ports:
      - "8080:8080"
    volumes:
      - /home/docker/xxl-job/log:/data/applogs
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://172.22.77.108:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=kun_mysql"
    privileged: true
    restart: always
    depends_on:
      - mysql
  # 服务注册与发现
  nacos:
    container_name: nacos
    image: nacos/nacos-server:v2.1.1
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - /home/docker/nacos/logs:/home/nacos/logs
      - /home/docker/nacos/conf/application.properties:/home/nacos/conf/application.properties
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=1g
      - JVM_XMX=1g
    privileged: true
    restart: always
    depends_on:
      - mysql