version : '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    restart: always
    privileged: true
    volumes:
      - /home/docker/mysql/conf:/etc/mysql/conf.d
      - /home/docker/mysql/logs:/var/log
      - /home/docker/mysql/data:/var/lib/mysql
      - /home/docker/mysql/mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: kun_mysql
  nacos:
    container_name: nacos
    image: nacos/nacos-server:v2.1.1
    privileged: true
    restart: always
    volumes:
      - /home/docker/nacos/logs:/home/nacos/logs
      - /home/docker/nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=1g
      - JVM_XMX=1g
    depends_on:
      - mysql